<a href="https://colab.research.google.com/github/moonjunseok/moon-python/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

기본적으로 array라는 단위로 데이터를 관리하며, 이에 대해 연산을 수행합니다.

array는 말 그대로 행렬이라는 개념입니다.


In [ ]:
# numpy 설치

import numpy as np

In [ ]:
# arry 정의 및 사용하기

data1=[1,2,3,4,5]
data2=[1,2,3,3.5,4]

In [ ]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
# shape : array의 형태(크기)를 확인할 수 있다.
arr1.shape  # (5,) <- 1행 5열

(5,)

In [ ]:
# array 의 자료형을 확인 할 수 있다.
arr1.dtype

dtype('int64')

In [ ]:
arr2 = np.array(data2)
arr2

array([1. , 2. , 3. , 3.5, 4. ])

In [ ]:
arr2.dtype  # data2 

dtype('float64')

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr3.shape # 4행 3열

(4, 3)

In [ ]:
# Ndarray는 각 원소별로 동일한 데이터 타입으로 처리 할 수 있습니다.
# array([원소,원소,...,n개 , dtype= ]) 이런식으로 하면 모든 원소를 같은 타입으로 변경이 가능합니다.

In [ ]:
A=[1,2,3,4]

a=np.array(A, np.int)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


In [ ]:
b=np.array(A,np.str)
print(type(b))
print(b)

<class 'numpy.ndarray'>
['1' '2' '3' '4']


In [ ]:
c=np.array(A,np.float)
print(type(c))
print(c)

<class 'numpy.ndarray'>
[1. 2. 3. 4.]


In [ ]:
# Ndarray 타입을 검색하거나 슬라이싱은 참조만 할당하므로 변경을 방지하기 위해서는 
# 새로운 ndarray로 만들어 사용할때는 .copy 메소드가 필요합니다.

# 주소를 공유하는 것이 아닌, 새로운 주소를 할당하여 배열을 복사하고 싶다면 .copy 사용

arr = np.array([1,2,3])
arr  

array([1, 2, 3])

In [ ]:
new = arr.copy()
new

array([1, 2, 3])

In [ ]:
new[0] = 3  #이렇게 카피한 new 배열에 [0]에 3을 넣어줍니다.

In [ ]:
arr   # 카피당한 arr에는 1,2,3 이 계속 있고

array([1, 2, 3])

In [ ]:
new   # 카피한 new에는 3,2,3이 나온다. 

array([3, 2, 3])

**벡터화**: 배열은 for문을 작성하지 않고 데이터를 일괄 처리 
하는것

*   같은 크기의 배열 간의 산술 연산은 배열의 각 원소 단위로 적용됨


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.shape  # 2행 3열

(2, 3)

In [ ]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.]])

**브로드캐스팅**

*   다른 모양의 배연 간의 산술 연산을 수행 할 수 있도록 해주는 numpy의 기능
*   브로드 캐스팅이 가능하려면 연산을 수행하는 축을 제외한 나머지 축의 shape이 일치하거나 둘 중 하나의 길이가 1이여야함.
*  다른 배열들 간의 연산이 어떤 조건을 만족했을 때 가능해지도록 배열을 자동적으로 변환하는 것



In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr2=np.array([10,11,12])
arr2

array([10, 11, 12])

In [ ]:
arr2.shape

(3,)

In [ ]:
# 두 배열의 행렬이 다르지만 계산이 가능하다. 브로드캐스팅 때문에

arr1+arr2    

array([[11, 13, 15],
       [14, 16, 18]])

In [ ]:
a=arr1*arr2
a

array([[10, 22, 36],
       [40, 55, 72]])

In [ ]:
a.shape

(2, 3)

In [ ]:
# 하나의 array에 스칼라 연산(각 원소 하나하나 씩에 계산)도 가능하다.
arr1 * 10  

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr1**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
# dtype

arr=np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [ ]:
# .astype(np.float64)
float_arr=arr.astype(np.float64)
float_arr

array([10., 20., 30., 40.])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.size  #.size : 배열에 있는 원소의 전체 갯수

6

In [ ]:
arr1.ndim  # .ndim : 배열의 차원의 갯수

2

In [ ]:
a= np.array(10)
print(a)
print(a.shape)
print(a.ndim)

10
()
0


ndarray attributes

In [ ]:
# zeros

np.zeros((5))

array([0., 0., 0., 0., 0.])

In [ ]:
# ones

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# full

np.full((4),5)

array([5, 5, 5, 5])

In [ ]:
# identity

np.identity(5,dtype=int)  # N x N 정방행렬만 생성 가능

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# eye

np.eye(5,dtype=int)        # N x M 행렬도 생성가능

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# _like  : zeros_like, ones_like, full_like, empty_like
# shape을 명시하지 않고 기존에 존재하는 배열을 인자로 넘겨준다.

arr1 = np.array([[1,2,3,1],[2,4,5,6]])
arr1

array([[1, 2, 3, 1],
       [2, 4, 5, 6]])

In [ ]:
arr2= np.ones_like(arr1)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# arange : 내장 함수 range 와 유사한 역할, ndarray를 반환

np.arange(-3,3)

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [ ]:
np.arange(3,50,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

배열 결합 함수

In [ ]:
# Hstack, concatenate(axis=0)
# 두 배열을 왼쪽에서 오른쪽으로 붙이기.

a= np.array([1,2,3])

b= np.array([4,5,6])

In [ ]:
np.hstack([a,b])  

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# vstack, concatenate(axis=1)
# 두 배열을 위에서 아래로 붙이기.

np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate((a,b),axis=1)  #concatenate((a,b),axis=1) 같은 경우는 2차원 이상부터만 가능능

AxisError: ignored